sonar.projectKey=raschmitt_zapinit
sonar.organization=raschmitt

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=app/static/**

sonar.pullrequest.provider=github
sonar.pullrequest.github.repository=raschmitt/zapinit

sonar.qualitygate.wait=true

sonar.newCodePeriod.type=reference_branch
sonar.newCodePeriod.value=main
